server:
  port: 8082

spring:
  datasource:
    url: ${EVENT_DB_URL:jdbc:postgresql://localhost:5432/event_processor}
    username: ${EVENT_DB_USER:postgres}
    password: ${EVENT_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    listener:
      simple:
        default-requeue-rejected: false

app:
  messaging:
    exchange: ${RABBITMQ_EVENTS_EXCHANGE:fitbeat.events}
    queue: ${EVENT_QUEUE_NAME:fitbeat.event-processor.q}
    dlq: ${EVENT_DLQ_NAME:fitbeat.event-processor.dlq}
    source: ${EVENT_SOURCE:event-processor}
  goals:
    weekly-sessions: ${WEEKLY_SESSIONS_GOAL:3}
