server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # 👇 Esto redirige las rutas del frontend a React Router de forma segura
        try_files $uri $uri/ /index.html;
    }

    # El Ingress de GKE se encargará de interceptar /api y mandarlo al backend,
    # así que Nginx aquí solo se preocupa por servir el HTML/JS estático.
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}